//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NareshIT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployee
    {
        [Required(ErrorMessage ="*")]
        public int empId { get; set; }
        [Required(ErrorMessage = "*")]
        public string empName { get; set; }
        [Required(ErrorMessage = "*")]
        [EmailAddress]
        public string empEmail { get; set; }
        public string gender { get; set; }
        [Required(ErrorMessage = "*")]
        public string contact { get; set; }
        [Required(ErrorMessage = "*")]
        public Nullable<int> salary { get; set; }
        public string city { get; set; }
        public Nullable<int> departmentId { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
